### ISSUE TITLE
IndexError: arrays used as indices must be of integer or boolean type

### ISSUE THREAD

**Issue by Freestyleyang** [kristianfoerster/melodist#7]
Hi There,

Thank you for developing such an excellent package for disaggregating climate variables from daily to hourly.

I have followed the "examples.ipynb", however, an error occurs when I try to run "**_data_obs_hourly = melodist.util.drop_incomplete_days(data_obs_hourly)_**". It shows "**IndexError: arrays used as indices must be of integer or boolean type**". Could you please help me with this issue? I am running Python 3.11.3, thank you.

![Error](https://github.com/kristianfoerster/melodist/assets/20953347/3d31832e-68a4-43cf-8178-8c509f9cecf9)

**Comment by fhanzer** [comment]
Hi @Freestyleyang,

thank you for reporting these issues! I can confirm them; the errors are due to incompatibilities with recent pandas and numpy versions.
I've now pushed a commit that should resolve the issues. We will publish a new release on PyPI, but in the meantime you could install the development version from GitHub (`pip install --force-reinstall --no-deps git+https://github.com/kristianfoerster/melodist.git`).

**Comment by Freestyleyang** [comment]
Hi @fhanzer,

Thank you very much for your reply. I have installed the updated module from GitHub.

The calculation goes smoothly, however, when I try to plot the results, an error occurs: `<input>:8: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like frame[string], is deprecated and will be removed in a future version. Use frame.loc[string] instead.` Could you please check?

I am using Python 3.9, pandas 1.5.3, numpy 1.24.3, scipy 1.10.1, and matplotlib 3.7.1.

**Comment by fhanzer** [comment]
Could you share your code where this warning occurs? And, does running the example notebook (examples.ipynb) now work with your setup or are there any issues as well?

**Comment by Freestyleyang** [comment]
Sure! When I run the `examples.ipynb`, a warning occurs at `stats.calc_humidity_stats()`: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.

When I run `precip5min_example.ipynb`, all calculations run smoothly. However, `plot(cumsum=True)` returns no figure. A figure does not show up. Thank you. 

I am using Python 3.9, pandas 1.5.3, numpy 1.24.3, scipy 1.10.1, and matplotlib 3.7.1.

**Comment by fhanzer** [comment]
Hi!

I just pushed another commit which should remove the warning, but this should not be the issue.
I just tried to run the examples notebook in a fresh virtualenv using your package versions (`pip install 'pandas==1.5.3' 'numpy==1.24.3' 'scipy==1.10.1' 'matplotlib==3.7.1' git+https://github.com/kristianfoerster/melodist.git`), and for me everything works as expected.

Could you check if the data is disaggregated correctly and only the plots are not shown?
E.g., if you run

```python
station.disaggregate_temperature(method='sine_min_max')
print(station.data_disagg.temp)
```

in the examples.ipynb notebook, the result should be

```
2014-01-01 00:00:00    271.411731
2014-01-01 01:00:00    271.142000
2014-01-01 02:00:00    271.050000
2014-01-01 03:00:00    271.142000
2014-01-01 04:00:00    271.411731
                          ...    
2016-12-31 19:00:00    269.049406
2016-12-31 20:00:00    268.700000
2016-12-31 21:00:00    268.350594
2016-12-31 22:00:00    268.025000
2016-12-31 23:00:00    267.745406
Freq: H, Name: temp, Length: 26304, dtype: float64
```

**Comment by Freestyleyang** [comment]
Hi,

I just tried to run `examples.ipynb`. No more warnings occurred and figures showed correctly!

When I try to run `precip5min_example.ipynb`, all calculations went smoothly. However, `plot(cumsum=True)` did not return a figure. This may be fixed by adding `plt.show()` after `plt.tight_layout()` in the `def plot(cumsum=False):`. Thank you.

**Comment by fhanzer** [comment]
Ok, great that it works now!
And thanks for the suggestion, I have now added a `plt.show()` command to the precip5min_example.ipynb (in my setup the plots were displayed also without the `plt.show()`)!
